---
- name: Tasks for all servers
  gather_facts: false
  hosts: all_Splunk_test
  become: yes
  become_method: sudo

  vars:
    ansible_user: ec2-user
    # ansible_ssh_private_key_file: /home/ec2-user/demo_keypairs.pem

  roles:
    - { role: common, tags: ['common', 'common-base'] }